source 'https://github.com/lf-sytc/LFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'LFBaseViewController_Example' do
  pod 'LFBaseViewController', :path => '../'
  
end
